from __future__ import annotations

from typing import Dict, List


def canada_keyword_groups() -> List[Dict[str, List[str]]]:
    return [
        {
            "label": "canada",
            "terms": [
                "Canada",
                "Canadian",
                "Gouvernement du Canada",
                "Government of Canada",
                "Open Data Canada",
                "Open Government Canada",
                "Statistique Canada",
                "Statistics Canada",
            ],
        },
        {
            "label": "ontario",
            "terms": [
                "Ontario",
                "National Capital Region",
                "Région de la capitale nationale",
                "Barrie",
                "Belleville",
                "Brampton",
                "Brant",
                "Brantford",
                "Brockville",
                "Burlington",
                "Cambridge",
                "Clarence-Rockland",
                "Clarence Rockland",
                "Cornwall",
                "Dryden",
                "Elliot Lake",
                "Greater Sudbury",
                "Guelph",
                "Haldimand County",
                "Hamilton",
                "Kawartha Lakes",
                "Kenora",
                "Kingston",
                "Kitchener",
                "London",
                "Markham",
                "Mississauga",
                "Niagara Falls",
                "Norfolk County",
                "North Bay",
                "Orillia",
                "Oshawa",
                "Ottawa",
                "Owen Sound",
                "Pembroke",
                "Peterborough",
                "Pickering",
                "Port Colborne",
                "Prince Edward County",
                "Quinte West",
                "Richmond Hill",
                "Sarnia",
                "Sault Ste. Marie",
                "Sault Ste Marie",
                "St. Catharines",
                "St Catharines",
                "St. Thomas",
                "St Thomas",
                "Stratford",
                "Temiskaming Shores",
                "Thorold",
                "Thunder Bay",
                "Timmins",
                "Toronto",
                "Vaughan",
                "Waterloo",
                "Welland",
                "Windsor",
                "Woodstock",
                "London Ontario",
                "London, Ontario",
                "Niagara",
                "Sudbury",
                "Whitby",
                "Ajax",
                "Newmarket",
                "Oakville",
                "Halton",
                "Peel",
                "York Region",
                "Durham Region",
                "Simcoe",
                "Muskoka",
                "Algonquin",
                "Northern Ontario",
            ],
        },
        {
            "label": "quebec",
            "terms": [
                "Quebec",
                "Québec",
                "Montreal",
                "Montréal",
                "Laval",
                "Gatineau",
                "Québec City",
                "Quebec City",
                "Ville de Québec",
                "Trois-Rivières",
                "Trois-Rivieres",
                "Saguenay",
                "Sherbrooke",
                "Longueuil",
                "Brossard",
                "Drummondville",
                "Rimouski",
                "Saint-Hyacinthe",
                "Saint-Jean-sur-Richelieu",
                "Outaouais",
                "Abitibi",
                "Abitibi-Témiscamingue",
                "Gaspésie",
                "Gaspesie",
                "Chaudière-Appalaches",
                "Chaudiere-Appalaches",
                "Bas-Saint-Laurent",
            ],
        },
        {
            "label": "bc",
            "terms": [
                "British Columbia",
                "Colombie-Britannique",
                "BC",
                "B.C.",
                "Vancouver Island",
                "Okanagan",
                "Abbotsford",
                "Armstrong",
                "Burnaby",
                "Campbell River",
                "Castlegar",
                "Chilliwack",
                "Colwood",
                "Coquitlam",
                "Courtenay",
                "Cranbrook",
                "Dawson Creek",
                "Delta",
                "Duncan",
                "Enderby",
                "Fernie",
                "Fort St. John",
                "Grand Forks",
                "Greenwood",
                "Kamloops",
                "Kelowna",
                "Kimberley",
                "Kitimat",
                "Langford",
                "Langley",
                "Maple Ridge",
                "Merritt",
                "Mission",
                "Nanaimo",
                "Nelson",
                "New Westminster",
                "North Vancouver",
                "Parksville",
                "Penticton",
                "Pitt Meadows",
                "Port Alberni",
                "Port Coquitlam",
                "Port Moody",
                "Powell River",
                "Prince George",
                "Prince Rupert",
                "Quesnel",
                "Revelstoke",
                "Richmond",
                "Rossland",
                "Salmon Arm",
                "Surrey",
                "Terrace",
                "Trail",
                "Vancouver",
                "Vernon",
                "Victoria",
                "West Kelowna",
                "White Rock",
                "Williams Lake",
            ],
        },
        {
            "label": "alberta",
            "terms": [
                "Alberta",
                "Airdrie",
                "Beaumont",
                "Brooks",
                "Calgary",
                "Camrose",
                "Chestermere",
                "Cold Lake",
                "Edmonton",
                "Fort Saskatchewan",
                "Grande Prairie",
                "Lacombe",
                "Leduc",
                "Lethbridge",
                "Lloydminster",
                "Medicine Hat",
                "Red Deer",
                "Spruce Grove",
                "St. Albert",
                "Wetaskiwin",
                "Fort McMurray",
                "Wood Buffalo",
            ],
        },
        {
            "label": "manitoba",
            "terms": [
                "Manitoba",
                "Brandon",
                "Dauphin",
                "Flin Flon",
                "Morden",
                "Portage la Prairie",
                "Selkirk",
                "Steinbach",
                "Thompson",
                "Winkler",
                "Winnipeg",
            ],
        },
        {
            "label": "saskatchewan",
            "terms": [
                "Saskatchewan",
                "Estevan",
                "Flin Flon",
                "Humboldt",
                "Lloydminster",
                "Martensville",
                "Meadow Lake",
                "Melfort",
                "Melville",
                "Moose Jaw",
                "North Battleford",
                "Prince Albert",
                "Regina",
                "Saskatoon",
                "Swift Current",
                "Warman",
                "Weyburn",
                "Yorkton",
            ],
        },
        {
            "label": "nova_scotia",
            "terms": [
                "Nova Scotia",
                "Nouvelle-Écosse",
                "Halifax",
                "Halifax Regional Municipality",
                "Dartmouth",
                "Sydney Nova Scotia",
                "Cape Breton",
                "Cape Breton Regional Municipality",
                "Region of Queens",
                "West Hants",
                "West Hants Regional Municipality",
                "Amherst",
                "Annapolis Royal",
                "Antigonish",
                "Berwick",
                "Bridgewater",
                "Clark's Harbour",
                "Digby",
                "Kentville",
                "Lockeport",
                "Lunenburg",
                "Mahone Bay",
                "Middleton",
                "Mulgrave",
                "New Glasgow",
                "Oxford",
                "Pictou",
                "Port Hawkesbury",
                "Shelburne",
                "Stellarton",
                "Stewiacke",
                "Trenton",
                "Truro",
                "Westville",
                "Wolfville",
                "Yarmouth",
            ],
        },
        {
            "label": "new_brunswick",
            "terms": [
                "New Brunswick",
                "Nouveau-Brunswick",
                "Bathurst",
                "Campbellton",
                "Dieppe",
                "Edmundston",
                "Fredericton",
                "Miramichi",
                "Moncton",
                "Saint John",
                "Saint John New Brunswick",
            ],
        },
        {"label": "pei", "terms": ["Prince Edward Island", "Île-du-Prince-Édouard", "Charlottetown", "Summerside"]},
        {
            "label": "newfoundland",
            "terms": [
                "Newfoundland",
                "Labrador",
                "Newfoundland and Labrador",
                "Terre-Neuve-et-Labrador",
                "St. John's",
                "St Johns",
                "Corner Brook",
                "Mount Pearl",
                "Gander",
            ],
        },
        {"label": "yukon", "terms": ["Yukon", "Whitehorse", "Dawson City"]},
        {
            "label": "nwt",
            "terms": ["Northwest Territories", "Territoires du Nord-Ouest", "Yellowknife", "Hay River", "Inuvik"],
        },
        {"label": "nunavut", "terms": ["Nunavut", "Iqaluit", "Rankin Inlet", "Cambridge Bay"]},
    ]
